// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Walletrpc {
  public static class VersionService
  {
    static readonly string __ServiceName = "walletrpc.VersionService";

    static readonly Marshaller<global::Walletrpc.VersionRequest> __Marshaller_VersionRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.VersionRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.VersionResponse> __Marshaller_VersionResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.VersionResponse.Parser.ParseFrom);

    static readonly Method<global::Walletrpc.VersionRequest, global::Walletrpc.VersionResponse> __Method_Version = new Method<global::Walletrpc.VersionRequest, global::Walletrpc.VersionResponse>(
        MethodType.Unary,
        __ServiceName,
        "Version",
        __Marshaller_VersionRequest,
        __Marshaller_VersionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Walletrpc.ApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VersionService</summary>
    public abstract class VersionServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.VersionResponse> Version(global::Walletrpc.VersionRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for VersionService</summary>
    public class VersionServiceClient : ClientBase<VersionServiceClient>
    {
      /// <summary>Creates a new client for VersionService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public VersionServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for VersionService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public VersionServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected VersionServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected VersionServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Walletrpc.VersionResponse Version(global::Walletrpc.VersionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Version(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.VersionResponse Version(global::Walletrpc.VersionRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Version, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.VersionResponse> VersionAsync(global::Walletrpc.VersionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return VersionAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.VersionResponse> VersionAsync(global::Walletrpc.VersionRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Version, null, options, request);
      }
      protected override VersionServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new VersionServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(VersionServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Version, serviceImpl.Version).Build();
    }

  }
  public static class WalletService
  {
    static readonly string __ServiceName = "walletrpc.WalletService";

    static readonly Marshaller<global::Walletrpc.PingRequest> __Marshaller_PingRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PingRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.PingResponse> __Marshaller_PingResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PingResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NetworkRequest> __Marshaller_NetworkRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NetworkRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NetworkResponse> __Marshaller_NetworkResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NetworkResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountNumberRequest> __Marshaller_AccountNumberRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountNumberRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountNumberResponse> __Marshaller_AccountNumberResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountNumberResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountsRequest> __Marshaller_AccountsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountsResponse> __Marshaller_AccountsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.BalanceRequest> __Marshaller_BalanceRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.BalanceRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.BalanceResponse> __Marshaller_BalanceResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.BalanceResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.GetTransactionsRequest> __Marshaller_GetTransactionsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.GetTransactionsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.GetTransactionsResponse> __Marshaller_GetTransactionsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.GetTransactionsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.TicketPriceRequest> __Marshaller_TicketPriceRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.TicketPriceRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.TicketPriceResponse> __Marshaller_TicketPriceResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.TicketPriceResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.StakeInfoRequest> __Marshaller_StakeInfoRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.StakeInfoRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.StakeInfoResponse> __Marshaller_StakeInfoResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.StakeInfoResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.TransactionNotificationsRequest> __Marshaller_TransactionNotificationsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.TransactionNotificationsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.TransactionNotificationsResponse> __Marshaller_TransactionNotificationsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.TransactionNotificationsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SpentnessNotificationsRequest> __Marshaller_SpentnessNotificationsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SpentnessNotificationsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SpentnessNotificationsResponse> __Marshaller_SpentnessNotificationsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SpentnessNotificationsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountNotificationsRequest> __Marshaller_AccountNotificationsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountNotificationsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.AccountNotificationsResponse> __Marshaller_AccountNotificationsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.AccountNotificationsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ChangePassphraseRequest> __Marshaller_ChangePassphraseRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ChangePassphraseRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ChangePassphraseResponse> __Marshaller_ChangePassphraseResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ChangePassphraseResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.RenameAccountRequest> __Marshaller_RenameAccountRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.RenameAccountRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.RenameAccountResponse> __Marshaller_RenameAccountResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.RenameAccountResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.RescanRequest> __Marshaller_RescanRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.RescanRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.RescanResponse> __Marshaller_RescanResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.RescanResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NextAccountRequest> __Marshaller_NextAccountRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NextAccountRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NextAccountResponse> __Marshaller_NextAccountResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NextAccountResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NextAddressRequest> __Marshaller_NextAddressRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NextAddressRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.NextAddressResponse> __Marshaller_NextAddressResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.NextAddressResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ImportPrivateKeyRequest> __Marshaller_ImportPrivateKeyRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ImportPrivateKeyRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ImportPrivateKeyResponse> __Marshaller_ImportPrivateKeyResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ImportPrivateKeyResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ImportScriptRequest> __Marshaller_ImportScriptRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ImportScriptRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.ImportScriptResponse> __Marshaller_ImportScriptResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.ImportScriptResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.FundTransactionRequest> __Marshaller_FundTransactionRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.FundTransactionRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.FundTransactionResponse> __Marshaller_FundTransactionResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.FundTransactionResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SignTransactionRequest> __Marshaller_SignTransactionRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SignTransactionRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SignTransactionResponse> __Marshaller_SignTransactionResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SignTransactionResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.PublishTransactionRequest> __Marshaller_PublishTransactionRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PublishTransactionRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.PublishTransactionResponse> __Marshaller_PublishTransactionResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PublishTransactionResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.PurchaseTicketsRequest> __Marshaller_PurchaseTicketsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PurchaseTicketsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.PurchaseTicketsResponse> __Marshaller_PurchaseTicketsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.PurchaseTicketsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.LoadActiveDataFiltersRequest> __Marshaller_LoadActiveDataFiltersRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.LoadActiveDataFiltersRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.LoadActiveDataFiltersResponse> __Marshaller_LoadActiveDataFiltersResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.LoadActiveDataFiltersResponse.Parser.ParseFrom);

    static readonly Method<global::Walletrpc.PingRequest, global::Walletrpc.PingResponse> __Method_Ping = new Method<global::Walletrpc.PingRequest, global::Walletrpc.PingResponse>(
        MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_PingRequest,
        __Marshaller_PingResponse);

    static readonly Method<global::Walletrpc.NetworkRequest, global::Walletrpc.NetworkResponse> __Method_Network = new Method<global::Walletrpc.NetworkRequest, global::Walletrpc.NetworkResponse>(
        MethodType.Unary,
        __ServiceName,
        "Network",
        __Marshaller_NetworkRequest,
        __Marshaller_NetworkResponse);

    static readonly Method<global::Walletrpc.AccountNumberRequest, global::Walletrpc.AccountNumberResponse> __Method_AccountNumber = new Method<global::Walletrpc.AccountNumberRequest, global::Walletrpc.AccountNumberResponse>(
        MethodType.Unary,
        __ServiceName,
        "AccountNumber",
        __Marshaller_AccountNumberRequest,
        __Marshaller_AccountNumberResponse);

    static readonly Method<global::Walletrpc.AccountsRequest, global::Walletrpc.AccountsResponse> __Method_Accounts = new Method<global::Walletrpc.AccountsRequest, global::Walletrpc.AccountsResponse>(
        MethodType.Unary,
        __ServiceName,
        "Accounts",
        __Marshaller_AccountsRequest,
        __Marshaller_AccountsResponse);

    static readonly Method<global::Walletrpc.BalanceRequest, global::Walletrpc.BalanceResponse> __Method_Balance = new Method<global::Walletrpc.BalanceRequest, global::Walletrpc.BalanceResponse>(
        MethodType.Unary,
        __ServiceName,
        "Balance",
        __Marshaller_BalanceRequest,
        __Marshaller_BalanceResponse);

    static readonly Method<global::Walletrpc.GetTransactionsRequest, global::Walletrpc.GetTransactionsResponse> __Method_GetTransactions = new Method<global::Walletrpc.GetTransactionsRequest, global::Walletrpc.GetTransactionsResponse>(
        MethodType.Unary,
        __ServiceName,
        "GetTransactions",
        __Marshaller_GetTransactionsRequest,
        __Marshaller_GetTransactionsResponse);

    static readonly Method<global::Walletrpc.TicketPriceRequest, global::Walletrpc.TicketPriceResponse> __Method_TicketPrice = new Method<global::Walletrpc.TicketPriceRequest, global::Walletrpc.TicketPriceResponse>(
        MethodType.Unary,
        __ServiceName,
        "TicketPrice",
        __Marshaller_TicketPriceRequest,
        __Marshaller_TicketPriceResponse);

    static readonly Method<global::Walletrpc.StakeInfoRequest, global::Walletrpc.StakeInfoResponse> __Method_StakeInfo = new Method<global::Walletrpc.StakeInfoRequest, global::Walletrpc.StakeInfoResponse>(
        MethodType.Unary,
        __ServiceName,
        "StakeInfo",
        __Marshaller_StakeInfoRequest,
        __Marshaller_StakeInfoResponse);

    static readonly Method<global::Walletrpc.TransactionNotificationsRequest, global::Walletrpc.TransactionNotificationsResponse> __Method_TransactionNotifications = new Method<global::Walletrpc.TransactionNotificationsRequest, global::Walletrpc.TransactionNotificationsResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "TransactionNotifications",
        __Marshaller_TransactionNotificationsRequest,
        __Marshaller_TransactionNotificationsResponse);

    static readonly Method<global::Walletrpc.SpentnessNotificationsRequest, global::Walletrpc.SpentnessNotificationsResponse> __Method_SpentnessNotifications = new Method<global::Walletrpc.SpentnessNotificationsRequest, global::Walletrpc.SpentnessNotificationsResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "SpentnessNotifications",
        __Marshaller_SpentnessNotificationsRequest,
        __Marshaller_SpentnessNotificationsResponse);

    static readonly Method<global::Walletrpc.AccountNotificationsRequest, global::Walletrpc.AccountNotificationsResponse> __Method_AccountNotifications = new Method<global::Walletrpc.AccountNotificationsRequest, global::Walletrpc.AccountNotificationsResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "AccountNotifications",
        __Marshaller_AccountNotificationsRequest,
        __Marshaller_AccountNotificationsResponse);

    static readonly Method<global::Walletrpc.ChangePassphraseRequest, global::Walletrpc.ChangePassphraseResponse> __Method_ChangePassphrase = new Method<global::Walletrpc.ChangePassphraseRequest, global::Walletrpc.ChangePassphraseResponse>(
        MethodType.Unary,
        __ServiceName,
        "ChangePassphrase",
        __Marshaller_ChangePassphraseRequest,
        __Marshaller_ChangePassphraseResponse);

    static readonly Method<global::Walletrpc.RenameAccountRequest, global::Walletrpc.RenameAccountResponse> __Method_RenameAccount = new Method<global::Walletrpc.RenameAccountRequest, global::Walletrpc.RenameAccountResponse>(
        MethodType.Unary,
        __ServiceName,
        "RenameAccount",
        __Marshaller_RenameAccountRequest,
        __Marshaller_RenameAccountResponse);

    static readonly Method<global::Walletrpc.RescanRequest, global::Walletrpc.RescanResponse> __Method_Rescan = new Method<global::Walletrpc.RescanRequest, global::Walletrpc.RescanResponse>(
        MethodType.ServerStreaming,
        __ServiceName,
        "Rescan",
        __Marshaller_RescanRequest,
        __Marshaller_RescanResponse);

    static readonly Method<global::Walletrpc.NextAccountRequest, global::Walletrpc.NextAccountResponse> __Method_NextAccount = new Method<global::Walletrpc.NextAccountRequest, global::Walletrpc.NextAccountResponse>(
        MethodType.Unary,
        __ServiceName,
        "NextAccount",
        __Marshaller_NextAccountRequest,
        __Marshaller_NextAccountResponse);

    static readonly Method<global::Walletrpc.NextAddressRequest, global::Walletrpc.NextAddressResponse> __Method_NextAddress = new Method<global::Walletrpc.NextAddressRequest, global::Walletrpc.NextAddressResponse>(
        MethodType.Unary,
        __ServiceName,
        "NextAddress",
        __Marshaller_NextAddressRequest,
        __Marshaller_NextAddressResponse);

    static readonly Method<global::Walletrpc.ImportPrivateKeyRequest, global::Walletrpc.ImportPrivateKeyResponse> __Method_ImportPrivateKey = new Method<global::Walletrpc.ImportPrivateKeyRequest, global::Walletrpc.ImportPrivateKeyResponse>(
        MethodType.Unary,
        __ServiceName,
        "ImportPrivateKey",
        __Marshaller_ImportPrivateKeyRequest,
        __Marshaller_ImportPrivateKeyResponse);

    static readonly Method<global::Walletrpc.ImportScriptRequest, global::Walletrpc.ImportScriptResponse> __Method_ImportScript = new Method<global::Walletrpc.ImportScriptRequest, global::Walletrpc.ImportScriptResponse>(
        MethodType.Unary,
        __ServiceName,
        "ImportScript",
        __Marshaller_ImportScriptRequest,
        __Marshaller_ImportScriptResponse);

    static readonly Method<global::Walletrpc.FundTransactionRequest, global::Walletrpc.FundTransactionResponse> __Method_FundTransaction = new Method<global::Walletrpc.FundTransactionRequest, global::Walletrpc.FundTransactionResponse>(
        MethodType.Unary,
        __ServiceName,
        "FundTransaction",
        __Marshaller_FundTransactionRequest,
        __Marshaller_FundTransactionResponse);

    static readonly Method<global::Walletrpc.SignTransactionRequest, global::Walletrpc.SignTransactionResponse> __Method_SignTransaction = new Method<global::Walletrpc.SignTransactionRequest, global::Walletrpc.SignTransactionResponse>(
        MethodType.Unary,
        __ServiceName,
        "SignTransaction",
        __Marshaller_SignTransactionRequest,
        __Marshaller_SignTransactionResponse);

    static readonly Method<global::Walletrpc.PublishTransactionRequest, global::Walletrpc.PublishTransactionResponse> __Method_PublishTransaction = new Method<global::Walletrpc.PublishTransactionRequest, global::Walletrpc.PublishTransactionResponse>(
        MethodType.Unary,
        __ServiceName,
        "PublishTransaction",
        __Marshaller_PublishTransactionRequest,
        __Marshaller_PublishTransactionResponse);

    static readonly Method<global::Walletrpc.PurchaseTicketsRequest, global::Walletrpc.PurchaseTicketsResponse> __Method_PurchaseTickets = new Method<global::Walletrpc.PurchaseTicketsRequest, global::Walletrpc.PurchaseTicketsResponse>(
        MethodType.Unary,
        __ServiceName,
        "PurchaseTickets",
        __Marshaller_PurchaseTicketsRequest,
        __Marshaller_PurchaseTicketsResponse);

    static readonly Method<global::Walletrpc.LoadActiveDataFiltersRequest, global::Walletrpc.LoadActiveDataFiltersResponse> __Method_LoadActiveDataFilters = new Method<global::Walletrpc.LoadActiveDataFiltersRequest, global::Walletrpc.LoadActiveDataFiltersResponse>(
        MethodType.Unary,
        __ServiceName,
        "LoadActiveDataFilters",
        __Marshaller_LoadActiveDataFiltersRequest,
        __Marshaller_LoadActiveDataFiltersResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Walletrpc.ApiReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of WalletService</summary>
    public abstract class WalletServiceBase
    {
      /// <summary>
      ///  Queries
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.PingResponse> Ping(global::Walletrpc.PingRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.NetworkResponse> Network(global::Walletrpc.NetworkRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.AccountNumberResponse> AccountNumber(global::Walletrpc.AccountNumberRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.AccountsResponse> Accounts(global::Walletrpc.AccountsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.BalanceResponse> Balance(global::Walletrpc.BalanceRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.GetTransactionsResponse> GetTransactions(global::Walletrpc.GetTransactionsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.TicketPriceResponse> TicketPrice(global::Walletrpc.TicketPriceRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.StakeInfoResponse> StakeInfo(global::Walletrpc.StakeInfoRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Notifications
      /// </summary>
      public virtual global::System.Threading.Tasks.Task TransactionNotifications(global::Walletrpc.TransactionNotificationsRequest request, IServerStreamWriter<global::Walletrpc.TransactionNotificationsResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SpentnessNotifications(global::Walletrpc.SpentnessNotificationsRequest request, IServerStreamWriter<global::Walletrpc.SpentnessNotificationsResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task AccountNotifications(global::Walletrpc.AccountNotificationsRequest request, IServerStreamWriter<global::Walletrpc.AccountNotificationsResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  Control
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.ChangePassphraseResponse> ChangePassphrase(global::Walletrpc.ChangePassphraseRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.RenameAccountResponse> RenameAccount(global::Walletrpc.RenameAccountRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task Rescan(global::Walletrpc.RescanRequest request, IServerStreamWriter<global::Walletrpc.RescanResponse> responseStream, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.NextAccountResponse> NextAccount(global::Walletrpc.NextAccountRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.NextAddressResponse> NextAddress(global::Walletrpc.NextAddressRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.ImportPrivateKeyResponse> ImportPrivateKey(global::Walletrpc.ImportPrivateKeyRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.ImportScriptResponse> ImportScript(global::Walletrpc.ImportScriptRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.FundTransactionResponse> FundTransaction(global::Walletrpc.FundTransactionRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.SignTransactionResponse> SignTransaction(global::Walletrpc.SignTransactionRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.PublishTransactionResponse> PublishTransaction(global::Walletrpc.PublishTransactionRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.PurchaseTicketsResponse> PurchaseTickets(global::Walletrpc.PurchaseTicketsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.LoadActiveDataFiltersResponse> LoadActiveDataFilters(global::Walletrpc.LoadActiveDataFiltersRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WalletService</summary>
    public class WalletServiceClient : ClientBase<WalletServiceClient>
    {
      /// <summary>Creates a new client for WalletService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WalletServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WalletService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WalletServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WalletServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WalletServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  Queries
      /// </summary>
      public virtual global::Walletrpc.PingResponse Ping(global::Walletrpc.PingRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Ping(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Queries
      /// </summary>
      public virtual global::Walletrpc.PingResponse Ping(global::Walletrpc.PingRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>
      ///  Queries
      /// </summary>
      public virtual AsyncUnaryCall<global::Walletrpc.PingResponse> PingAsync(global::Walletrpc.PingRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PingAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Queries
      /// </summary>
      public virtual AsyncUnaryCall<global::Walletrpc.PingResponse> PingAsync(global::Walletrpc.PingRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual global::Walletrpc.NetworkResponse Network(global::Walletrpc.NetworkRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Network(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.NetworkResponse Network(global::Walletrpc.NetworkRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Network, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NetworkResponse> NetworkAsync(global::Walletrpc.NetworkRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return NetworkAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NetworkResponse> NetworkAsync(global::Walletrpc.NetworkRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Network, null, options, request);
      }
      public virtual global::Walletrpc.AccountNumberResponse AccountNumber(global::Walletrpc.AccountNumberRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AccountNumber(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.AccountNumberResponse AccountNumber(global::Walletrpc.AccountNumberRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AccountNumber, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.AccountNumberResponse> AccountNumberAsync(global::Walletrpc.AccountNumberRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AccountNumberAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.AccountNumberResponse> AccountNumberAsync(global::Walletrpc.AccountNumberRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AccountNumber, null, options, request);
      }
      public virtual global::Walletrpc.AccountsResponse Accounts(global::Walletrpc.AccountsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Accounts(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.AccountsResponse Accounts(global::Walletrpc.AccountsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Accounts, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.AccountsResponse> AccountsAsync(global::Walletrpc.AccountsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AccountsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.AccountsResponse> AccountsAsync(global::Walletrpc.AccountsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Accounts, null, options, request);
      }
      public virtual global::Walletrpc.BalanceResponse Balance(global::Walletrpc.BalanceRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Balance(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.BalanceResponse Balance(global::Walletrpc.BalanceRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Balance, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.BalanceResponse> BalanceAsync(global::Walletrpc.BalanceRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return BalanceAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.BalanceResponse> BalanceAsync(global::Walletrpc.BalanceRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Balance, null, options, request);
      }
      public virtual global::Walletrpc.GetTransactionsResponse GetTransactions(global::Walletrpc.GetTransactionsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetTransactions(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.GetTransactionsResponse GetTransactions(global::Walletrpc.GetTransactionsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTransactions, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.GetTransactionsResponse> GetTransactionsAsync(global::Walletrpc.GetTransactionsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetTransactionsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.GetTransactionsResponse> GetTransactionsAsync(global::Walletrpc.GetTransactionsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTransactions, null, options, request);
      }
      public virtual global::Walletrpc.TicketPriceResponse TicketPrice(global::Walletrpc.TicketPriceRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TicketPrice(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.TicketPriceResponse TicketPrice(global::Walletrpc.TicketPriceRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TicketPrice, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.TicketPriceResponse> TicketPriceAsync(global::Walletrpc.TicketPriceRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TicketPriceAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.TicketPriceResponse> TicketPriceAsync(global::Walletrpc.TicketPriceRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TicketPrice, null, options, request);
      }
      public virtual global::Walletrpc.StakeInfoResponse StakeInfo(global::Walletrpc.StakeInfoRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StakeInfo(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.StakeInfoResponse StakeInfo(global::Walletrpc.StakeInfoRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StakeInfo, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.StakeInfoResponse> StakeInfoAsync(global::Walletrpc.StakeInfoRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StakeInfoAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.StakeInfoResponse> StakeInfoAsync(global::Walletrpc.StakeInfoRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StakeInfo, null, options, request);
      }
      /// <summary>
      ///  Notifications
      /// </summary>
      public virtual AsyncServerStreamingCall<global::Walletrpc.TransactionNotificationsResponse> TransactionNotifications(global::Walletrpc.TransactionNotificationsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return TransactionNotifications(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Notifications
      /// </summary>
      public virtual AsyncServerStreamingCall<global::Walletrpc.TransactionNotificationsResponse> TransactionNotifications(global::Walletrpc.TransactionNotificationsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_TransactionNotifications, null, options, request);
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.SpentnessNotificationsResponse> SpentnessNotifications(global::Walletrpc.SpentnessNotificationsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SpentnessNotifications(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.SpentnessNotificationsResponse> SpentnessNotifications(global::Walletrpc.SpentnessNotificationsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SpentnessNotifications, null, options, request);
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.AccountNotificationsResponse> AccountNotifications(global::Walletrpc.AccountNotificationsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return AccountNotifications(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.AccountNotificationsResponse> AccountNotifications(global::Walletrpc.AccountNotificationsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_AccountNotifications, null, options, request);
      }
      /// <summary>
      ///  Control
      /// </summary>
      public virtual global::Walletrpc.ChangePassphraseResponse ChangePassphrase(global::Walletrpc.ChangePassphraseRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ChangePassphrase(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Control
      /// </summary>
      public virtual global::Walletrpc.ChangePassphraseResponse ChangePassphrase(global::Walletrpc.ChangePassphraseRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ChangePassphrase, null, options, request);
      }
      /// <summary>
      ///  Control
      /// </summary>
      public virtual AsyncUnaryCall<global::Walletrpc.ChangePassphraseResponse> ChangePassphraseAsync(global::Walletrpc.ChangePassphraseRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ChangePassphraseAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  Control
      /// </summary>
      public virtual AsyncUnaryCall<global::Walletrpc.ChangePassphraseResponse> ChangePassphraseAsync(global::Walletrpc.ChangePassphraseRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ChangePassphrase, null, options, request);
      }
      public virtual global::Walletrpc.RenameAccountResponse RenameAccount(global::Walletrpc.RenameAccountRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RenameAccount(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.RenameAccountResponse RenameAccount(global::Walletrpc.RenameAccountRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RenameAccount, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.RenameAccountResponse> RenameAccountAsync(global::Walletrpc.RenameAccountRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RenameAccountAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.RenameAccountResponse> RenameAccountAsync(global::Walletrpc.RenameAccountRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RenameAccount, null, options, request);
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.RescanResponse> Rescan(global::Walletrpc.RescanRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Rescan(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncServerStreamingCall<global::Walletrpc.RescanResponse> Rescan(global::Walletrpc.RescanRequest request, CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Rescan, null, options, request);
      }
      public virtual global::Walletrpc.NextAccountResponse NextAccount(global::Walletrpc.NextAccountRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return NextAccount(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.NextAccountResponse NextAccount(global::Walletrpc.NextAccountRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_NextAccount, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NextAccountResponse> NextAccountAsync(global::Walletrpc.NextAccountRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return NextAccountAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NextAccountResponse> NextAccountAsync(global::Walletrpc.NextAccountRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_NextAccount, null, options, request);
      }
      public virtual global::Walletrpc.NextAddressResponse NextAddress(global::Walletrpc.NextAddressRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return NextAddress(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.NextAddressResponse NextAddress(global::Walletrpc.NextAddressRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_NextAddress, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NextAddressResponse> NextAddressAsync(global::Walletrpc.NextAddressRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return NextAddressAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.NextAddressResponse> NextAddressAsync(global::Walletrpc.NextAddressRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_NextAddress, null, options, request);
      }
      public virtual global::Walletrpc.ImportPrivateKeyResponse ImportPrivateKey(global::Walletrpc.ImportPrivateKeyRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportPrivateKey(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.ImportPrivateKeyResponse ImportPrivateKey(global::Walletrpc.ImportPrivateKeyRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImportPrivateKey, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.ImportPrivateKeyResponse> ImportPrivateKeyAsync(global::Walletrpc.ImportPrivateKeyRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportPrivateKeyAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.ImportPrivateKeyResponse> ImportPrivateKeyAsync(global::Walletrpc.ImportPrivateKeyRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImportPrivateKey, null, options, request);
      }
      public virtual global::Walletrpc.ImportScriptResponse ImportScript(global::Walletrpc.ImportScriptRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportScript(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.ImportScriptResponse ImportScript(global::Walletrpc.ImportScriptRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ImportScript, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.ImportScriptResponse> ImportScriptAsync(global::Walletrpc.ImportScriptRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return ImportScriptAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.ImportScriptResponse> ImportScriptAsync(global::Walletrpc.ImportScriptRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ImportScript, null, options, request);
      }
      public virtual global::Walletrpc.FundTransactionResponse FundTransaction(global::Walletrpc.FundTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FundTransaction(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.FundTransactionResponse FundTransaction(global::Walletrpc.FundTransactionRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FundTransaction, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.FundTransactionResponse> FundTransactionAsync(global::Walletrpc.FundTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FundTransactionAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.FundTransactionResponse> FundTransactionAsync(global::Walletrpc.FundTransactionRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FundTransaction, null, options, request);
      }
      public virtual global::Walletrpc.SignTransactionResponse SignTransaction(global::Walletrpc.SignTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SignTransaction(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.SignTransactionResponse SignTransaction(global::Walletrpc.SignTransactionRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SignTransaction, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.SignTransactionResponse> SignTransactionAsync(global::Walletrpc.SignTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SignTransactionAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.SignTransactionResponse> SignTransactionAsync(global::Walletrpc.SignTransactionRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SignTransaction, null, options, request);
      }
      public virtual global::Walletrpc.PublishTransactionResponse PublishTransaction(global::Walletrpc.PublishTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PublishTransaction(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.PublishTransactionResponse PublishTransaction(global::Walletrpc.PublishTransactionRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PublishTransaction, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.PublishTransactionResponse> PublishTransactionAsync(global::Walletrpc.PublishTransactionRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PublishTransactionAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.PublishTransactionResponse> PublishTransactionAsync(global::Walletrpc.PublishTransactionRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PublishTransaction, null, options, request);
      }
      public virtual global::Walletrpc.PurchaseTicketsResponse PurchaseTickets(global::Walletrpc.PurchaseTicketsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PurchaseTickets(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.PurchaseTicketsResponse PurchaseTickets(global::Walletrpc.PurchaseTicketsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PurchaseTickets, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.PurchaseTicketsResponse> PurchaseTicketsAsync(global::Walletrpc.PurchaseTicketsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return PurchaseTicketsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.PurchaseTicketsResponse> PurchaseTicketsAsync(global::Walletrpc.PurchaseTicketsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PurchaseTickets, null, options, request);
      }
      public virtual global::Walletrpc.LoadActiveDataFiltersResponse LoadActiveDataFilters(global::Walletrpc.LoadActiveDataFiltersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return LoadActiveDataFilters(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.LoadActiveDataFiltersResponse LoadActiveDataFilters(global::Walletrpc.LoadActiveDataFiltersRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LoadActiveDataFilters, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.LoadActiveDataFiltersResponse> LoadActiveDataFiltersAsync(global::Walletrpc.LoadActiveDataFiltersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return LoadActiveDataFiltersAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.LoadActiveDataFiltersResponse> LoadActiveDataFiltersAsync(global::Walletrpc.LoadActiveDataFiltersRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LoadActiveDataFilters, null, options, request);
      }
      protected override WalletServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WalletServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(WalletServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping)
          .AddMethod(__Method_Network, serviceImpl.Network)
          .AddMethod(__Method_AccountNumber, serviceImpl.AccountNumber)
          .AddMethod(__Method_Accounts, serviceImpl.Accounts)
          .AddMethod(__Method_Balance, serviceImpl.Balance)
          .AddMethod(__Method_GetTransactions, serviceImpl.GetTransactions)
          .AddMethod(__Method_TicketPrice, serviceImpl.TicketPrice)
          .AddMethod(__Method_StakeInfo, serviceImpl.StakeInfo)
          .AddMethod(__Method_TransactionNotifications, serviceImpl.TransactionNotifications)
          .AddMethod(__Method_SpentnessNotifications, serviceImpl.SpentnessNotifications)
          .AddMethod(__Method_AccountNotifications, serviceImpl.AccountNotifications)
          .AddMethod(__Method_ChangePassphrase, serviceImpl.ChangePassphrase)
          .AddMethod(__Method_RenameAccount, serviceImpl.RenameAccount)
          .AddMethod(__Method_Rescan, serviceImpl.Rescan)
          .AddMethod(__Method_NextAccount, serviceImpl.NextAccount)
          .AddMethod(__Method_NextAddress, serviceImpl.NextAddress)
          .AddMethod(__Method_ImportPrivateKey, serviceImpl.ImportPrivateKey)
          .AddMethod(__Method_ImportScript, serviceImpl.ImportScript)
          .AddMethod(__Method_FundTransaction, serviceImpl.FundTransaction)
          .AddMethod(__Method_SignTransaction, serviceImpl.SignTransaction)
          .AddMethod(__Method_PublishTransaction, serviceImpl.PublishTransaction)
          .AddMethod(__Method_PurchaseTickets, serviceImpl.PurchaseTickets)
          .AddMethod(__Method_LoadActiveDataFilters, serviceImpl.LoadActiveDataFilters).Build();
    }

  }
  public static class WalletLoaderService
  {
    static readonly string __ServiceName = "walletrpc.WalletLoaderService";

    static readonly Marshaller<global::Walletrpc.WalletExistsRequest> __Marshaller_WalletExistsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.WalletExistsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.WalletExistsResponse> __Marshaller_WalletExistsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.WalletExistsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.CreateWalletRequest> __Marshaller_CreateWalletRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.CreateWalletRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.CreateWalletResponse> __Marshaller_CreateWalletResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.CreateWalletResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.OpenWalletRequest> __Marshaller_OpenWalletRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.OpenWalletRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.OpenWalletResponse> __Marshaller_OpenWalletResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.OpenWalletResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.CloseWalletRequest> __Marshaller_CloseWalletRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.CloseWalletRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.CloseWalletResponse> __Marshaller_CloseWalletResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.CloseWalletResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.StartConsensusRpcRequest> __Marshaller_StartConsensusRpcRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.StartConsensusRpcRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.StartConsensusRpcResponse> __Marshaller_StartConsensusRpcResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.StartConsensusRpcResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.DiscoverAddressesRequest> __Marshaller_DiscoverAddressesRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.DiscoverAddressesRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.DiscoverAddressesResponse> __Marshaller_DiscoverAddressesResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.DiscoverAddressesResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SubscribeToBlockNotificationsRequest> __Marshaller_SubscribeToBlockNotificationsRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SubscribeToBlockNotificationsRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.SubscribeToBlockNotificationsResponse> __Marshaller_SubscribeToBlockNotificationsResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.SubscribeToBlockNotificationsResponse.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.FetchHeadersRequest> __Marshaller_FetchHeadersRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.FetchHeadersRequest.Parser.ParseFrom);
    static readonly Marshaller<global::Walletrpc.FetchHeadersResponse> __Marshaller_FetchHeadersResponse = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Walletrpc.FetchHeadersResponse.Parser.ParseFrom);

    static readonly Method<global::Walletrpc.WalletExistsRequest, global::Walletrpc.WalletExistsResponse> __Method_WalletExists = new Method<global::Walletrpc.WalletExistsRequest, global::Walletrpc.WalletExistsResponse>(
        MethodType.Unary,
        __ServiceName,
        "WalletExists",
        __Marshaller_WalletExistsRequest,
        __Marshaller_WalletExistsResponse);

    static readonly Method<global::Walletrpc.CreateWalletRequest, global::Walletrpc.CreateWalletResponse> __Method_CreateWallet = new Method<global::Walletrpc.CreateWalletRequest, global::Walletrpc.CreateWalletResponse>(
        MethodType.Unary,
        __ServiceName,
        "CreateWallet",
        __Marshaller_CreateWalletRequest,
        __Marshaller_CreateWalletResponse);

    static readonly Method<global::Walletrpc.OpenWalletRequest, global::Walletrpc.OpenWalletResponse> __Method_OpenWallet = new Method<global::Walletrpc.OpenWalletRequest, global::Walletrpc.OpenWalletResponse>(
        MethodType.Unary,
        __ServiceName,
        "OpenWallet",
        __Marshaller_OpenWalletRequest,
        __Marshaller_OpenWalletResponse);

    static readonly Method<global::Walletrpc.CloseWalletRequest, global::Walletrpc.CloseWalletResponse> __Method_CloseWallet = new Method<global::Walletrpc.CloseWalletRequest, global::Walletrpc.CloseWalletResponse>(
        MethodType.Unary,
        __ServiceName,
        "CloseWallet",
        __Marshaller_CloseWalletRequest,
        __Marshaller_CloseWalletResponse);

    static readonly Method<global::Walletrpc.StartConsensusRpcRequest, global::Walletrpc.StartConsensusRpcResponse> __Method_StartConsensusRpc = new Method<global::Walletrpc.StartConsensusRpcRequest, global::Walletrpc.StartConsensusRpcResponse>(
        MethodType.Unary,
        __ServiceName,
        "StartConsensusRpc",
        __Marshaller_StartConsensusRpcRequest,
        __Marshaller_StartConsensusRpcResponse);

    static readonly Method<global::Walletrpc.DiscoverAddressesRequest, global::Walletrpc.DiscoverAddressesResponse> __Method_DiscoverAddresses = new Method<global::Walletrpc.DiscoverAddressesRequest, global::Walletrpc.DiscoverAddressesResponse>(
        MethodType.Unary,
        __ServiceName,
        "DiscoverAddresses",
        __Marshaller_DiscoverAddressesRequest,
        __Marshaller_DiscoverAddressesResponse);

    static readonly Method<global::Walletrpc.SubscribeToBlockNotificationsRequest, global::Walletrpc.SubscribeToBlockNotificationsResponse> __Method_SubscribeToBlockNotifications = new Method<global::Walletrpc.SubscribeToBlockNotificationsRequest, global::Walletrpc.SubscribeToBlockNotificationsResponse>(
        MethodType.Unary,
        __ServiceName,
        "SubscribeToBlockNotifications",
        __Marshaller_SubscribeToBlockNotificationsRequest,
        __Marshaller_SubscribeToBlockNotificationsResponse);

    static readonly Method<global::Walletrpc.FetchHeadersRequest, global::Walletrpc.FetchHeadersResponse> __Method_FetchHeaders = new Method<global::Walletrpc.FetchHeadersRequest, global::Walletrpc.FetchHeadersResponse>(
        MethodType.Unary,
        __ServiceName,
        "FetchHeaders",
        __Marshaller_FetchHeadersRequest,
        __Marshaller_FetchHeadersResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Walletrpc.ApiReflection.Descriptor.Services[2]; }
    }

    /// <summary>Base class for server-side implementations of WalletLoaderService</summary>
    public abstract class WalletLoaderServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.WalletExistsResponse> WalletExists(global::Walletrpc.WalletExistsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.CreateWalletResponse> CreateWallet(global::Walletrpc.CreateWalletRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.OpenWalletResponse> OpenWallet(global::Walletrpc.OpenWalletRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.CloseWalletResponse> CloseWallet(global::Walletrpc.CloseWalletRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.StartConsensusRpcResponse> StartConsensusRpc(global::Walletrpc.StartConsensusRpcRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.DiscoverAddressesResponse> DiscoverAddresses(global::Walletrpc.DiscoverAddressesRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.SubscribeToBlockNotificationsResponse> SubscribeToBlockNotifications(global::Walletrpc.SubscribeToBlockNotificationsRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Walletrpc.FetchHeadersResponse> FetchHeaders(global::Walletrpc.FetchHeadersRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WalletLoaderService</summary>
    public class WalletLoaderServiceClient : ClientBase<WalletLoaderServiceClient>
    {
      /// <summary>Creates a new client for WalletLoaderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WalletLoaderServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WalletLoaderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WalletLoaderServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WalletLoaderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WalletLoaderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Walletrpc.WalletExistsResponse WalletExists(global::Walletrpc.WalletExistsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return WalletExists(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.WalletExistsResponse WalletExists(global::Walletrpc.WalletExistsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_WalletExists, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.WalletExistsResponse> WalletExistsAsync(global::Walletrpc.WalletExistsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return WalletExistsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.WalletExistsResponse> WalletExistsAsync(global::Walletrpc.WalletExistsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_WalletExists, null, options, request);
      }
      public virtual global::Walletrpc.CreateWalletResponse CreateWallet(global::Walletrpc.CreateWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateWallet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.CreateWalletResponse CreateWallet(global::Walletrpc.CreateWalletRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWallet, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.CreateWalletResponse> CreateWalletAsync(global::Walletrpc.CreateWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CreateWalletAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.CreateWalletResponse> CreateWalletAsync(global::Walletrpc.CreateWalletRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWallet, null, options, request);
      }
      public virtual global::Walletrpc.OpenWalletResponse OpenWallet(global::Walletrpc.OpenWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return OpenWallet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.OpenWalletResponse OpenWallet(global::Walletrpc.OpenWalletRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_OpenWallet, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.OpenWalletResponse> OpenWalletAsync(global::Walletrpc.OpenWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return OpenWalletAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.OpenWalletResponse> OpenWalletAsync(global::Walletrpc.OpenWalletRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_OpenWallet, null, options, request);
      }
      public virtual global::Walletrpc.CloseWalletResponse CloseWallet(global::Walletrpc.CloseWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CloseWallet(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.CloseWalletResponse CloseWallet(global::Walletrpc.CloseWalletRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CloseWallet, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.CloseWalletResponse> CloseWalletAsync(global::Walletrpc.CloseWalletRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return CloseWalletAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.CloseWalletResponse> CloseWalletAsync(global::Walletrpc.CloseWalletRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CloseWallet, null, options, request);
      }
      public virtual global::Walletrpc.StartConsensusRpcResponse StartConsensusRpc(global::Walletrpc.StartConsensusRpcRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StartConsensusRpc(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.StartConsensusRpcResponse StartConsensusRpc(global::Walletrpc.StartConsensusRpcRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_StartConsensusRpc, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.StartConsensusRpcResponse> StartConsensusRpcAsync(global::Walletrpc.StartConsensusRpcRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return StartConsensusRpcAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.StartConsensusRpcResponse> StartConsensusRpcAsync(global::Walletrpc.StartConsensusRpcRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_StartConsensusRpc, null, options, request);
      }
      public virtual global::Walletrpc.DiscoverAddressesResponse DiscoverAddresses(global::Walletrpc.DiscoverAddressesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DiscoverAddresses(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.DiscoverAddressesResponse DiscoverAddresses(global::Walletrpc.DiscoverAddressesRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DiscoverAddresses, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.DiscoverAddressesResponse> DiscoverAddressesAsync(global::Walletrpc.DiscoverAddressesRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DiscoverAddressesAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.DiscoverAddressesResponse> DiscoverAddressesAsync(global::Walletrpc.DiscoverAddressesRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DiscoverAddresses, null, options, request);
      }
      public virtual global::Walletrpc.SubscribeToBlockNotificationsResponse SubscribeToBlockNotifications(global::Walletrpc.SubscribeToBlockNotificationsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubscribeToBlockNotifications(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.SubscribeToBlockNotificationsResponse SubscribeToBlockNotifications(global::Walletrpc.SubscribeToBlockNotificationsRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SubscribeToBlockNotifications, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.SubscribeToBlockNotificationsResponse> SubscribeToBlockNotificationsAsync(global::Walletrpc.SubscribeToBlockNotificationsRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubscribeToBlockNotificationsAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.SubscribeToBlockNotificationsResponse> SubscribeToBlockNotificationsAsync(global::Walletrpc.SubscribeToBlockNotificationsRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SubscribeToBlockNotifications, null, options, request);
      }
      public virtual global::Walletrpc.FetchHeadersResponse FetchHeaders(global::Walletrpc.FetchHeadersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FetchHeaders(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Walletrpc.FetchHeadersResponse FetchHeaders(global::Walletrpc.FetchHeadersRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FetchHeaders, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Walletrpc.FetchHeadersResponse> FetchHeadersAsync(global::Walletrpc.FetchHeadersRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return FetchHeadersAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Walletrpc.FetchHeadersResponse> FetchHeadersAsync(global::Walletrpc.FetchHeadersRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FetchHeaders, null, options, request);
      }
      protected override WalletLoaderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WalletLoaderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(WalletLoaderServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_WalletExists, serviceImpl.WalletExists)
          .AddMethod(__Method_CreateWallet, serviceImpl.CreateWallet)
          .AddMethod(__Method_OpenWallet, serviceImpl.OpenWallet)
          .AddMethod(__Method_CloseWallet, serviceImpl.CloseWallet)
          .AddMethod(__Method_StartConsensusRpc, serviceImpl.StartConsensusRpc)
          .AddMethod(__Method_DiscoverAddresses, serviceImpl.DiscoverAddresses)
          .AddMethod(__Method_SubscribeToBlockNotifications, serviceImpl.SubscribeToBlockNotifications)
          .AddMethod(__Method_FetchHeaders, serviceImpl.FetchHeaders).Build();
    }

  }
}
#endregion
