// Code generated by "stringer -type=TicketStatus -linecomment"; DO NOT EDIT.

package wallet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TicketStatusUnknown-0]
	_ = x[TicketStatusUnmined-1]
	_ = x[TicketStatusImmature-2]
	_ = x[TicketStatusLive-3]
	_ = x[TicketStatusVoted-4]
	_ = x[TicketStatusMissed-5]
	_ = x[TicketStatusExpired-6]
	_ = x[TicketStatusUnspent-7]
	_ = x[TicketStatusRevoked-8]
}

const _TicketStatus_name = "unknownunminedimmaturelivevotedmissedexpiredunspentrevoked"

var _TicketStatus_index = [...]uint8{0, 7, 14, 22, 26, 31, 37, 44, 51, 58}

func (i TicketStatus) String() string {
	if i >= TicketStatus(len(_TicketStatus_index)-1) {
		return "TicketStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TicketStatus_name[_TicketStatus_index[i]:_TicketStatus_index[i+1]]
}
