// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dicemix.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerInfo struct {
	PeerId               uint32   `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Pk                   []byte   `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Sharedkey            []byte   `protobuf:"bytes,3,opt,name=sharedkey,proto3" json:"sharedkey,omitempty"`
	NumMsg               uint32   `protobuf:"varint,4,opt,name=num_msg,json=numMsg,proto3" json:"num_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{0}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (dst *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(dst, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *PeerInfo) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

func (m *PeerInfo) GetSharedkey() []byte {
	if m != nil {
		return m.Sharedkey
	}
	return nil
}

func (m *PeerInfo) GetNumMsg() uint32 {
	if m != nil {
		return m.NumMsg
	}
	return 0
}

type CoinJoinReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinJoinReq) Reset()         { *m = CoinJoinReq{} }
func (m *CoinJoinReq) String() string { return proto.CompactTextString(m) }
func (*CoinJoinReq) ProtoMessage()    {}
func (*CoinJoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{1}
}
func (m *CoinJoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinJoinReq.Unmarshal(m, b)
}
func (m *CoinJoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinJoinReq.Marshal(b, m, deterministic)
}
func (dst *CoinJoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinJoinReq.Merge(dst, src)
}
func (m *CoinJoinReq) XXX_Size() int {
	return xxx_messageInfo_CoinJoinReq.Size(m)
}
func (m *CoinJoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinJoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_CoinJoinReq proto.InternalMessageInfo

type CoinJoinRes struct {
	SessionId            uint32   `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	PeerIds              []uint64 `protobuf:"varint,4,rep,packed,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinJoinRes) Reset()         { *m = CoinJoinRes{} }
func (m *CoinJoinRes) String() string { return proto.CompactTextString(m) }
func (*CoinJoinRes) ProtoMessage()    {}
func (*CoinJoinRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{2}
}
func (m *CoinJoinRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinJoinRes.Unmarshal(m, b)
}
func (m *CoinJoinRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinJoinRes.Marshal(b, m, deterministic)
}
func (dst *CoinJoinRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinJoinRes.Merge(dst, src)
}
func (m *CoinJoinRes) XXX_Size() int {
	return xxx_messageInfo_CoinJoinRes.Size(m)
}
func (m *CoinJoinRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinJoinRes.DiscardUnknown(m)
}

var xxx_messageInfo_CoinJoinRes proto.InternalMessageInfo

func (m *CoinJoinRes) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CoinJoinRes) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *CoinJoinRes) GetPeerIds() []uint64 {
	if m != nil {
		return m.PeerIds
	}
	return nil
}

type KeyExchangeReq struct {
	SessionId            uint32   `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerId               uint32   `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	NumMsg               uint32   `protobuf:"varint,3,opt,name=num_msg,json=numMsg,proto3" json:"num_msg,omitempty"`
	Pk                   []byte   `protobuf:"bytes,4,opt,name=pk,proto3" json:"pk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeReq) Reset()         { *m = KeyExchangeReq{} }
func (m *KeyExchangeReq) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeReq) ProtoMessage()    {}
func (*KeyExchangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{3}
}
func (m *KeyExchangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeReq.Unmarshal(m, b)
}
func (m *KeyExchangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeReq.Marshal(b, m, deterministic)
}
func (dst *KeyExchangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeReq.Merge(dst, src)
}
func (m *KeyExchangeReq) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeReq.Size(m)
}
func (m *KeyExchangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeReq proto.InternalMessageInfo

func (m *KeyExchangeReq) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *KeyExchangeReq) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *KeyExchangeReq) GetNumMsg() uint32 {
	if m != nil {
		return m.NumMsg
	}
	return 0
}

func (m *KeyExchangeReq) GetPk() []byte {
	if m != nil {
		return m.Pk
	}
	return nil
}

type KeyExchangeRes struct {
	SessionId            uint32      `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerId               uint32      `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Peers                []*PeerInfo `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *KeyExchangeRes) Reset()         { *m = KeyExchangeRes{} }
func (m *KeyExchangeRes) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRes) ProtoMessage()    {}
func (*KeyExchangeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{4}
}
func (m *KeyExchangeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRes.Unmarshal(m, b)
}
func (m *KeyExchangeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRes.Marshal(b, m, deterministic)
}
func (dst *KeyExchangeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRes.Merge(dst, src)
}
func (m *KeyExchangeRes) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRes.Size(m)
}
func (m *KeyExchangeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRes.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRes proto.InternalMessageInfo

func (m *KeyExchangeRes) GetSessionId() uint32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *KeyExchangeRes) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *KeyExchangeRes) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

type DcExpVector struct {
	PeerId               uint32   `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Vector               []byte   `protobuf:"bytes,3,opt,name=vector,proto3" json:"vector,omitempty"`
	Commit               []byte   `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DcExpVector) Reset()         { *m = DcExpVector{} }
func (m *DcExpVector) String() string { return proto.CompactTextString(m) }
func (*DcExpVector) ProtoMessage()    {}
func (*DcExpVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{5}
}
func (m *DcExpVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DcExpVector.Unmarshal(m, b)
}
func (m *DcExpVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DcExpVector.Marshal(b, m, deterministic)
}
func (dst *DcExpVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DcExpVector.Merge(dst, src)
}
func (m *DcExpVector) XXX_Size() int {
	return xxx_messageInfo_DcExpVector.Size(m)
}
func (m *DcExpVector) XXX_DiscardUnknown() {
	xxx_messageInfo_DcExpVector.DiscardUnknown(m)
}

var xxx_messageInfo_DcExpVector proto.InternalMessageInfo

func (m *DcExpVector) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *DcExpVector) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *DcExpVector) GetVector() []byte {
	if m != nil {
		return m.Vector
	}
	return nil
}

func (m *DcExpVector) GetCommit() []byte {
	if m != nil {
		return m.Commit
	}
	return nil
}

type DcXorVector struct {
	PeerId               uint32   `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Len                  uint32   `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	Vector               []byte   `protobuf:"bytes,3,opt,name=vector,proto3" json:"vector,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DcXorVector) Reset()         { *m = DcXorVector{} }
func (m *DcXorVector) String() string { return proto.CompactTextString(m) }
func (*DcXorVector) ProtoMessage()    {}
func (*DcXorVector) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{6}
}
func (m *DcXorVector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DcXorVector.Unmarshal(m, b)
}
func (m *DcXorVector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DcXorVector.Marshal(b, m, deterministic)
}
func (dst *DcXorVector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DcXorVector.Merge(dst, src)
}
func (m *DcXorVector) XXX_Size() int {
	return xxx_messageInfo_DcXorVector.Size(m)
}
func (m *DcXorVector) XXX_DiscardUnknown() {
	xxx_messageInfo_DcXorVector.DiscardUnknown(m)
}

var xxx_messageInfo_DcXorVector proto.InternalMessageInfo

func (m *DcXorVector) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *DcXorVector) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *DcXorVector) GetVector() []byte {
	if m != nil {
		return m.Vector
	}
	return nil
}

type DcXorVectorResult struct {
	PeerIds              []uint32 `protobuf:"varint,1,rep,packed,name=peer_ids,json=peerIds,proto3" json:"peer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DcXorVectorResult) Reset()         { *m = DcXorVectorResult{} }
func (m *DcXorVectorResult) String() string { return proto.CompactTextString(m) }
func (*DcXorVectorResult) ProtoMessage()    {}
func (*DcXorVectorResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{7}
}
func (m *DcXorVectorResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DcXorVectorResult.Unmarshal(m, b)
}
func (m *DcXorVectorResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DcXorVectorResult.Marshal(b, m, deterministic)
}
func (dst *DcXorVectorResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DcXorVectorResult.Merge(dst, src)
}
func (m *DcXorVectorResult) XXX_Size() int {
	return xxx_messageInfo_DcXorVectorResult.Size(m)
}
func (m *DcXorVectorResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DcXorVectorResult.DiscardUnknown(m)
}

var xxx_messageInfo_DcXorVectorResult proto.InternalMessageInfo

func (m *DcXorVectorResult) GetPeerIds() []uint32 {
	if m != nil {
		return m.PeerIds
	}
	return nil
}

type AllMessages struct {
	Len                  uint32   `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Msgs                 []byte   `protobuf:"bytes,2,opt,name=msgs,proto3" json:"msgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllMessages) Reset()         { *m = AllMessages{} }
func (m *AllMessages) String() string { return proto.CompactTextString(m) }
func (*AllMessages) ProtoMessage()    {}
func (*AllMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{8}
}
func (m *AllMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllMessages.Unmarshal(m, b)
}
func (m *AllMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllMessages.Marshal(b, m, deterministic)
}
func (dst *AllMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllMessages.Merge(dst, src)
}
func (m *AllMessages) XXX_Size() int {
	return xxx_messageInfo_AllMessages.Size(m)
}
func (m *AllMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_AllMessages.DiscardUnknown(m)
}

var xxx_messageInfo_AllMessages proto.InternalMessageInfo

func (m *AllMessages) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *AllMessages) GetMsgs() []byte {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type TxInputs struct {
	PeerId               uint32   `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TicketPrice          int64    `protobuf:"varint,2,opt,name=ticket_price,json=ticketPrice,proto3" json:"ticket_price,omitempty"`
	Txins                []byte   `protobuf:"bytes,3,opt,name=txins,proto3" json:"txins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInputs) Reset()         { *m = TxInputs{} }
func (m *TxInputs) String() string { return proto.CompactTextString(m) }
func (*TxInputs) ProtoMessage()    {}
func (*TxInputs) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{9}
}
func (m *TxInputs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInputs.Unmarshal(m, b)
}
func (m *TxInputs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInputs.Marshal(b, m, deterministic)
}
func (dst *TxInputs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInputs.Merge(dst, src)
}
func (m *TxInputs) XXX_Size() int {
	return xxx_messageInfo_TxInputs.Size(m)
}
func (m *TxInputs) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInputs.DiscardUnknown(m)
}

var xxx_messageInfo_TxInputs proto.InternalMessageInfo

func (m *TxInputs) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *TxInputs) GetTicketPrice() int64 {
	if m != nil {
		return m.TicketPrice
	}
	return 0
}

func (m *TxInputs) GetTxins() []byte {
	if m != nil {
		return m.Txins
	}
	return nil
}

type JoinTx struct {
	PeerId               uint32   `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Tx                   []byte   `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinTx) Reset()         { *m = JoinTx{} }
func (m *JoinTx) String() string { return proto.CompactTextString(m) }
func (*JoinTx) ProtoMessage()    {}
func (*JoinTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_dicemix_1c42f0178567c795, []int{10}
}
func (m *JoinTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinTx.Unmarshal(m, b)
}
func (m *JoinTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinTx.Marshal(b, m, deterministic)
}
func (dst *JoinTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinTx.Merge(dst, src)
}
func (m *JoinTx) XXX_Size() int {
	return xxx_messageInfo_JoinTx.Size(m)
}
func (m *JoinTx) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinTx.DiscardUnknown(m)
}

var xxx_messageInfo_JoinTx proto.InternalMessageInfo

func (m *JoinTx) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *JoinTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerInfo)(nil), "messages.PeerInfo")
	proto.RegisterType((*CoinJoinReq)(nil), "messages.CoinJoinReq")
	proto.RegisterType((*CoinJoinRes)(nil), "messages.CoinJoinRes")
	proto.RegisterType((*KeyExchangeReq)(nil), "messages.KeyExchangeReq")
	proto.RegisterType((*KeyExchangeRes)(nil), "messages.KeyExchangeRes")
	proto.RegisterType((*DcExpVector)(nil), "messages.DcExpVector")
	proto.RegisterType((*DcXorVector)(nil), "messages.DcXorVector")
	proto.RegisterType((*DcXorVectorResult)(nil), "messages.DcXorVectorResult")
	proto.RegisterType((*AllMessages)(nil), "messages.AllMessages")
	proto.RegisterType((*TxInputs)(nil), "messages.TxInputs")
	proto.RegisterType((*JoinTx)(nil), "messages.JoinTx")
}

func init() { proto.RegisterFile("dicemix.proto", fileDescriptor_dicemix_1c42f0178567c795) }

var fileDescriptor_dicemix_1c42f0178567c795 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x93, 0xdf, 0xab, 0xd3, 0x30,
	0x14, 0xc7, 0xe9, 0x8f, 0xdb, 0xdb, 0x7b, 0x7a, 0x3b, 0x34, 0x88, 0x56, 0x50, 0xd0, 0x3c, 0xf5,
	0xa9, 0xa0, 0xfb, 0x0b, 0x44, 0xf7, 0x30, 0x65, 0x30, 0xca, 0x10, 0x1f, 0x84, 0x39, 0xdb, 0xd8,
	0xc5, 0xb5, 0x49, 0xd7, 0x64, 0xd2, 0xfd, 0xf7, 0x26, 0x6d, 0xca, 0xba, 0xc1, 0xf6, 0x20, 0x3e,
	0x0c, 0xce, 0xf9, 0x76, 0x39, 0x9f, 0x73, 0xce, 0x37, 0x81, 0x30, 0xa7, 0x19, 0xa9, 0x68, 0x9b,
	0xd4, 0x0d, 0x97, 0x1c, 0xf9, 0x15, 0x11, 0x62, 0x53, 0x10, 0x81, 0x7f, 0x83, 0xbf, 0x24, 0xa4,
	0x99, 0xb3, 0x5f, 0x1c, 0xbd, 0x80, 0xfb, 0x5a, 0xc5, 0x6b, 0x9a, 0x47, 0xd6, 0x1b, 0x2b, 0x0e,
	0x53, 0x4f, 0xa7, 0xf3, 0x1c, 0x4d, 0xc0, 0xae, 0x77, 0x91, 0xad, 0xb4, 0xc7, 0x54, 0x45, 0xe8,
	0x15, 0x3c, 0x88, 0xed, 0xa6, 0x21, 0xf9, 0x8e, 0x1c, 0x23, 0xa7, 0x93, 0x4f, 0x82, 0x2e, 0xc3,
	0x0e, 0xd5, 0xba, 0x12, 0x45, 0xe4, 0xf6, 0x65, 0x54, 0xba, 0x10, 0x05, 0x0e, 0x21, 0xf8, 0xc8,
	0x29, 0xfb, 0xac, 0x7e, 0x29, 0xd9, 0xe3, 0x1f, 0xe3, 0x54, 0xa0, 0xd7, 0x00, 0x42, 0x75, 0x45,
	0x39, 0xd3, 0x0d, 0xd8, 0xdd, 0xc9, 0x07, 0xa3, 0xa8, 0x1e, 0x46, 0xcd, 0x39, 0x67, 0xcd, 0xbd,
	0x04, 0xdf, 0x7c, 0x10, 0x8a, 0xe7, 0xc4, 0x6e, 0x7a, 0xdf, 0x7f, 0x11, 0x78, 0x0f, 0x93, 0x2f,
	0xe4, 0x38, 0x6b, 0xb3, 0xed, 0x86, 0x15, 0x44, 0x31, 0x2f, 0x20, 0xd6, 0x0d, 0x88, 0x7d, 0x06,
	0x19, 0xcd, 0xe4, 0x8c, 0x67, 0x32, 0xab, 0x71, 0x87, 0xd5, 0xe0, 0xe6, 0x02, 0x29, 0xfe, 0x19,
	0x19, 0xc3, 0x9d, 0x8e, 0x84, 0x02, 0x3a, 0x71, 0xf0, 0x1e, 0x25, 0x83, 0x67, 0xc9, 0x60, 0x58,
	0xda, 0xff, 0x01, 0x6f, 0x21, 0xf8, 0x94, 0xcd, 0xda, 0xfa, 0x2b, 0xc9, 0x24, 0x6f, 0xae, 0xdb,
	0xf8, 0x04, 0x9c, 0x92, 0x30, 0x83, 0xd1, 0x21, 0x7a, 0x0e, 0xde, 0x9f, 0xee, 0x90, 0x71, 0xd1,
	0x64, 0x5a, 0xcf, 0x78, 0x55, 0x51, 0x69, 0x26, 0x33, 0x19, 0x5e, 0x6a, 0xd2, 0x37, 0xde, 0xfc,
	0x37, 0x12, 0x4e, 0xe0, 0xe9, 0xa8, 0xa2, 0xda, 0xd7, 0xa1, 0x94, 0x67, 0x96, 0x5a, 0x6a, 0xfa,
	0xf0, 0x64, 0xe9, 0x14, 0x82, 0x0f, 0x65, 0xb9, 0x30, 0xab, 0x18, 0x40, 0xd6, 0x09, 0x84, 0xc0,
	0x55, 0x2e, 0x09, 0x73, 0x5b, 0xbb, 0x18, 0x7f, 0x07, 0x7f, 0xd5, 0xce, 0x59, 0x7d, 0x90, 0xe2,
	0x7a, 0xcf, 0x6f, 0xe1, 0x51, 0xd2, 0x6c, 0x47, 0xe4, 0xba, 0x6e, 0xd4, 0x63, 0xe9, 0x0a, 0x38,
	0x69, 0xd0, 0x6b, 0x4b, 0x2d, 0xa1, 0x67, 0x70, 0x27, 0x5b, 0xca, 0x84, 0x99, 0xa1, 0x4f, 0xf0,
	0x3b, 0xf0, 0xf4, 0x1d, 0x5e, 0xb5, 0x37, 0x1f, 0x90, 0x6c, 0xcd, 0x29, 0x15, 0xfd, 0xf4, 0xba,
	0x67, 0x38, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xef, 0xd3, 0x9e, 0x97, 0x03, 0x00, 0x00,
}
